---
- name: Ensures docker registry dir exists
  file:
    path: "{{ root_dir }}/registry/data"
    state: directory

- name: Adding htpasswd file
  template:
    src: ../templates/htpasswd.j2
    dest: "{{ root_dir }}/registry/data/htpasswd"
    mode: 0600

- name: Create the docker registry container
  docker_container:
    name: registry
    image: registry:2
    restart_policy: always
    networks:
      - name: internal
    volumes:
      - "{{ root_dir }}/registry/data:/var/lib/registry"
      - "{{ root_dir }}/registry/data/htpasswd:/auth/htpasswd"
    env:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: "/data"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_HTTP_SECRET: "{{ docker_registry.secret }}"
