---
- name: Ensures bookstack dir exists
  file:
    path: "{{ root_dir }}/bookstack"
    state: directory
    mode: 0755

- name: Ensures bookstack public uploads dir exists
  file:
    path: "{{ root_dir }}/bookstack/data/public"
    state: directory
    mode: 0755

- name: Ensures bookstack storage uploads dir exists
  file:
    path: "{{ root_dir }}/bookstack/data/storage"
    state: directory
    mode: 0755

- name: Create the bookstack container
  docker_container:
    name: bookstack
    image: solidnerd/bookstack:21.12
    restart_policy: unless-stopped
    networks:
      - name: web
      - name: internal
    volumes:
      - "{{ root_dir }}/bookstack/data/public:/var/www/bookstack/public/uploads"
      - "{{ root_dir }}/bookstack/data/storage:/var/www/bookstack/storage/uploads"
    labels:
      traefik.http.routers.bookstack.rule: "Host(`wiki.wertwein.com`)"
      traefik.http.services.bookstack.loadbalancer.server.port: "8080"
      traefik.enable: "true"
    env:
      APP_URL: "https://wiki.wertwein.com"
      DB_HOST: "mariadb"
      DB_DATABASE: "bookstack"
      DB_USERNAME: "{{ mariadb_user }}"
      DB_PASSWORD: "{{ mariadb_password }}"
