---
- name: Ensures traefik dir exists
  file:
    path: "{{ root_dir }}/traefik"
    state: directory

- name: Ensures acme.json file exists
  file:
    path: "{{ root_dir }}/traefik/acme.json"
    state: touch
    mode: 0600
    access_time: preserve
    modification_time: preserve

- name: Copy traefik configuration file
  template:
    src: traefik.yaml.j2
    dest: "{{ root_dir }}/traefik/traefik.yaml"
    mode: 0600

- name: Ensures traefik container is running
  docker_container:
    name: traefik
    image: traefik:v2.2.1
    restart_policy: always
    restart: true # TODO notify restart on container changes instead
    networks:
      - name: web
      - name: internal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ root_dir }}/traefik/traefik.yaml:/etc/traefik/traefik.yaml"
      - "{{ root_dir }}/traefik/acme.json:/etc/traefik/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      traefik.http.routers.traefik.rule: "Host(`routes.wertwein.com`)"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.routers.traefik.middlewares: "auth"
      traefik.http.services.traefik.loadbalancer.server.port: "8080"
      traefik.http.middlewares.auth.basicauth.users: "{{ traefik_user }}:{{ traefik_password | password_hash('bcrypt', traefik_salt) }}"
      traefik.enable: "true"
    env:
      NAMECHEAP_API_USER: "{{ namecheap_api_user }}"
      NAMECHEAP_API_KEY: "{{ namecheap_api_key }}"
