---
- name: Ensures firewall package is installed
  package:
    name: ufw
    state: latest

- name: Ensures ufw is running
  ufw:
    state: enabled

- name: Open firewall ports
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.protocol }}"
  with_items: "{{ firewall_allowed }}"
