---
- name: Ensure firewalld is running
  service:
    name: firewalld
    state: started
    enabled: true

- name: Open firewall ports
  firewalld:
    service: "{{ item }}"
    zone: public
    immediate: yes
    permanent: yes
    state: enabled
  with_items:
  - http
  - https
  - ssh

- name: Allow masquerading
  ansible.posix.firewalld:
    zone: public
    masquerade: "yes"
    immediate: yes
    permanent: yes
    state: enabled
