---
- name: Ensure firewalld is running
  service:
    name: firewalld
    state: started
    enabled: true

- name: Open firewall ports
  firewalld:
    port: "{{ item.port }}/{{ item.protocol }}"
    zone: public
    immediate: true
    permanent: true
    state: enabled
  with_items: "{{ firewall_allowed }}"

- name: Allow masquerading
  firewalld:
    zone: public
    masquerade: "yes"
    immediate: true
    permanent: true
    state: enabled
