---
- name: Configure hostname
  copy:
    content: "{{ hostname }}"
    dest: /etc/hostname
    mode: 0644

- name: Configure MOTD
  copy:
    src: login-info.sh
    dest: /etc/profile.d/login-info.sh
    owner: root
    group: root
    mode: 0644
