---
- name: Ensure OpenSSH server is installed
  ansible.builtin.package:
    name: openssh-server
    state: present

- name: Add user
  ansible.builtin.user:
    name: "{{ item.username }}"
    password: "{{ item.password | password_hash(salt=item.salt) }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    create_home: true
    home: "{{ item.home }}"
    state: present
  with_items: "{{ ssh_users }}"
  no_log: true

- name: Configure user sudo permissions
  ansible.builtin.lineinfile:
    dest: "/etc/sudoers.d/{{ item.username }}"
    line: "{{ item.username }} ALL=(ALL) NOPASSWD: ALL"
    create: true
    state: present
    validate: '/usr/sbin/visudo -cf %s'
    mode: "0440"
  with_items: "{{ ssh_users }}"
  no_log: true

- name: Set up users authorized_keys
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup('file', item.key) }}"
  with_items: "{{ ssh_users }}"
  no_log: true

- name: Harden SSH configuration
  ansible.builtin.template:
    src: sshd_config.j2
    dest: "/etc/ssh/sshd_config"
    mode: "0600"
  notify: Restart sshd
