---
- name: Add user
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    create_home: "{{ item.home | bool }}"
    home: "{{ item.home }}"
    state: present
  with_items: "{{ ssh_users }}"

- name: Configure user sudo permissions
  lineinfile:
    dest: "/etc/sudoers.d/{{ item.username }}"
    line: "{{ item.username }} ALL=(ALL) NOPASSWD: ALL"
    create: yes
    state: present
  with_items: "{{ ssh_users }}"

- name: Set up users authorized_keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup('file', '{{ item.key }}') }}"
  with_items: "{{ ssh_users }}"

- name: Harden SSH configuration
  template:
    src: sshd_config.j2
    dest: "/etc/ssh/sshd_config"
    mode: 0600
  notify: restart sshd
