---
- name: Ensures consul dir exists
  file:
    path: "{{ root_dir }}/consul/data"
    state: directory

- name: Create the consul container
  docker_container:
    name: consul-server
    image: consul:1.6
    command: agent -server -bootstrap -ui -client=0.0.0.0
    restart_policy: always
    purge_networks: yes
    networks:
#      - name: web
      - name: internal # required for registrator communication, but requires -bind arg
    volumes:
      - "{{ root_dir }}/consul/data:/consul/data"
    labels:
      traefik.http.routers.consul.rule: "Host(`cluster.wertwein.com`)"
      traefik.http.routers.consul.middlewares: auth
      traefik.http.services.consul.loadbalancer.server.port: "8500"
      traefik.http.middlewares.auth.basicAuth.users: "{{ traefik.user }}:{{ traefik.password | password_hash('bcrypt', traefik.salt) }}"
      traefik.docker.network: "internal"
      traefik.enable: "true"

- name: Create the registrator container
  docker_container:
    name: registrator
    image: gliderlabs/registrator:v7
    command: -internal -resync=60 -tags="eserver" consul://consul-server:8500
    restart_policy: always
    networks:
      - name: internal
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
