---
- name: Provisionning webservers group
  hosts: webservers
  vars:
    root_dir: '/opt'
    acme_email: example@example.com
    acme_provider: namecheap # https://docs.traefik.io/configuration/acme/#provider
    namecheap_api_user: username
    namecheap_api_key: api_key
    emil:
      password: password
      salt: secret
    birk:
      password: password
      salt: secret
    traefik:
      user: username
      password: password
      salt: secret
    postgres:
      user: user
      password: password
    mariadb:
      user: user
      password: password
    docker_registry:
      secret: secret
      users:
        - name: username
          password: password
          salt: secret
    domains:
      - name: example.com
        password: password
  roles:
    - docker
    - ddclient
    - mariadb
    - postgres
    - registry
    - watchtower
    - consul
    - portainer
    - omnidb
    - nexus
    - backup
    - bookstack
    - nextcloud
    - bitwarden
    - emil
    - birk
    - minecraft
    - minecraft_bedrock
    - traefik
