[project]
name = "eserver"
version = "0.1.0"
requires-python = "== 3.13.*"
authors = [{ name = "Isak Wertwein <isak.wertwein@gmail.com>" }]

dependencies = [
  "ansible == 12.1.*",
  "ansible-lint == 25.9.*",
  "ansible-vault == 4.1.*",
  "passlib == 1.7.*",
  "yamllint == 1.37.*",
]
