---
- name: Ensures ddclient dir exists
  file:
    path: "{{ root_dir }}/ddclient"
    state: directory

- name: Adding ddclient.conf file
  template:
    src: ../templates/ddclient.conf.j2
    dest: "{{ root_dir }}/ddclient/ddclient.conf"
    mode: 0600

- name: Create the ddclient container
  docker_container:
    name: ddclient
    image: mace/ddclient
    restart_policy: always
    volumes:
      - "{{ root_dir }}/ddclient/ddclient.conf:/config/ddclient.conf"
      - /etc/localtime:/etc/localtime.:ro
