---
- name: Include Minecraft Bedrock Edition tasks
  ansible.builtin.include_tasks: bedrock.yml
  when: "minecraft.bedrock.enabled | bool"
- name: Include Minecraft Java Edition tasks
  ansible.builtin.include_tasks: ftb.yml
  when: "minecraft.ftb.enabled | bool"
