---
# Setup SFTP access ?
# Make sure proper sshd config: https://gist.github.com/cmavr8/eb4a9e596bd0e3e85f97d907de288c54
# Restart sshd service if changed: https://raymii.org/s/tutorials/Ansible_-_Only-do-something-if-another-action-changed.html

- name: Ensure sftp group exists
  group:
    name: sftp
    state: present

- name: Ensures emil user exists
  user:
    name: emil
    password: "{{ emil_password | password_hash('sha512', emil_password_salt) }}"
    create_home: no
    home: "{{ root_dir }}/emil"
    shell: "/sbin/nologin"
    state: present

- name: Ensures http dir exists
  file:
    path: "{{ root_dir }}/httpd"
    state: directory

- name: Adding httpd.conf file
  template:
    src: ../templates/httpd.conf
    dest: "{{ root_dir }}/httpd/httpd.conf"
    mode: 0600

- name: Adding httpd-vhosts.conf file
  template:
    src: ../templates/httpd-vhosts.conf
    dest: "{{ root_dir }}/httpd/httpd-vhosts.conf"
    mode: 0600

- name: Ensures blog dir exists
  file:
    path: "{{ root_dir }}/emil/blog"
    owner: emil
    group: sftp
    mode: u=rwX,g=rX,o=rX
    state: directory

- name: Ensures portfolio dir exists
  file:
    path: "{{ root_dir }}/emil/emil"
    owner: emil
    group: sftp
    mode: u=rwX,g=rX,o=rX
    state: directory

- name: Ensures prometron dir exists
  file:
    path: "{{ root_dir }}/emil/prometron"
    owner: emil
    group: sftp
    mode: u=rwX,g=rX,o=rX
    state: directory

- name: Ensures smasharenas dir exists
  file:
    path: "{{ root_dir }}/emil/smasharenas"
    owner: emil
    group: sftp
    mode: u=rwX,g=rX,o=rX
    state: directory

- name: Create the httpd container
  docker_container:
    name: emil-httpd
    image: httpd:2.4-alpine
    restart_policy: unless-stopped
    networks:
      - name: web
    volumes:
      - "{{ root_dir }}/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "{{ root_dir }}/httpd/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf"
      - "{{ root_dir }}/emil/blog:/usr/local/apache2/htdocs/blog:ro"
      - "{{ root_dir }}/emil/emil:/usr/local/apache2/htdocs/emil:ro"
      - "{{ root_dir }}/emil/prometron:/usr/local/apache2/htdocs/prometron:ro"
      - "{{ root_dir }}/emil/smasharenas:/usr/local/apache2/htdocs/smasharenas:ro"
    labels:
      traefik.frontend.rule: "Host:blog.emil.wertwein.com,emil.wertwein.com,prometron.wertwein.com,smasharenas.com"
      traefik.frontend.redirect.entryPoint: https
      traefik.docker.network: "web"
      traefik.port: "80"
      traefik.enable: "true"
    env:
      VIRTUAL_HOST: "blog.emil.wertwein.com,emil.wertwein.com,prometron.wertwein.com,smasharenas.com"
      NAMECHEAP_API_USER: "{{ namecheap_api_user }}"
      NAMECHEAP_API_KEY: "{{ namecheap_api_key }}"
