---
root_dir: "{{ vault_root_dir }}"

ssh_port: "{{ vault_ssh_port }}"

firewall_allowed:
  - port: 80
    protocol: tcp
  - port: 443
    protocol: tcp
  - port: "{{ ssh_port }}"
    protocol: tcp
  - port: 1194  # VPN
    protocol: udp

docker_auth:
  - registry: ghcr.io
    username: "{{ vault_ghcr_username }}"
    password: "{{ vault_ghcr_password }}"
