---
- name: Restart server
  ansible.builtin.reboot:
    reboot_timeout: 300

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
    daemon_reload: true

- name: Cleanup authorized_keys
  ansible.builtin.file:
    state: absent
    path: "/home/{{ item.username }}/.ssh/authorized_keys"
  with_items:
    - "{{ ssh_users }}"
  no_log: true
