---
- include_tasks: mariadb.yml
  when: "mariadb_enabled is true"
- include_tasks: postgres.yml
  when: "postgres_enabled is true"
- include_tasks: omnidb.yml
  when: "mariadb_enabled is true or postgres_enabled is true"
