---
- name: Include MariaDB tasks
  ansible.builtin.include_tasks: mariadb.yml
  when: "mariadb_enabled is true"
- name: Include PostgreSQL tasks
  ansible.builtin.include_tasks: postgres.yml
  when: "postgres_enabled is true"
- name: Include OmniDB tasks
  ansible.builtin.include_tasks: omnidb.yml
  when: "mariadb_enabled is true or postgres_enabled is true"
