---
- name: Ensures mariadb dir exists
  file:
    path: "{{ root_dir }}/mariadb/data"
    state: directory
    mode: 0755

- name: Create the mariadb container
  docker_container:
    name: mariadb
    image: mariadb:10.5  # Nextcloud is broken on 10.6, see https://github.com/nextcloud/server/issues/25436#issuecomment-883213001
    restart_policy: unless-stopped
    networks:
      - name: internal
    volumes:
      - "{{ root_dir }}/mariadb/data:/var/lib/mysql"
    env:
      MYSQL_ROOT_USER: "{{ mariadb_user }}"
      MYSQL_ROOT_PASSWORD: "{{ mariadb_password }}"
      MYSQL_PORT: "{{ mariadb_port }}"
