---
- name: Ensures mariadb dir exists
  file:
    path: "{{ root_dir }}/mariadb/data"
    state: directory

- name: Create the mariadb container
  docker_container:
    name: mariadb
    image: mariadb:10
    restart_policy: unless-stopped
    networks:
      - name: internal
    volumes:
      - "{{ root_dir }}/mariadb/data:/var/lib/mysql"
    env:
      MYSQL_ROOT_USER: "{{ mariadb_user }}"
      MYSQL_ROOT_PASSWORD: "{{ mariadb_password }}"
      MYSQL_PORT: "{{ mariadb_port }}"
