---
- name: Ensures omnidb dir exists
  ansible.builtin.file:
    path: "{{ root_dir }}/omnidb/data"
    state: directory
    mode: 0777

- name: Copy omnidb configuration file
  ansible.builtin.copy:
    src: omnidb.conf
    dest: "{{ root_dir }}/omnidb/data/omnidb.conf"
    mode: 0644

- name: Create the omnidb container
  community.docker.docker_container:
    name: omnidb
    image: taivokasper/omnidb:v2.16.0-alpine_3.10
    restart_policy: always
    networks:
      - name: web
      - name: internal
    volumes:
      - "{{ root_dir }}/omnidb/data:/etc/omnidb"
    labels:
      traefik.http.routers.omnidb.rule: "Host(`db.wertwein.com`)"
      traefik.http.routers.omnidb.service: "omnidb"
      traefik.http.services.omnidb.loadbalancer.server.port: "8080"
      traefik.http.routers.omnidb-websocket.rule: "Host(`db.wertwein.com`) && PathPrefix(`/wss`)"
      traefik.http.routers.omnidb-websocket.service: "omnidb-websocket"
      traefik.http.services.omnidb-websocket.loadbalancer.server.port: "25482"
      traefik.enable: "true"
