---
- name: Ensures postgres dir exists
  file:
    path: "{{ root_dir }}/postgres/data"
    state: directory

- name: Create the postgres container
  docker_container:
    name: postgres
    image: postgres:11
    restart_policy: unless-stopped
    networks:
      - name: internal
    volumes:
      - "{{ root_dir }}/postgres/data:/var/lib/postgresql/data"
    env:
      POSTGRES_USER: "{{ postgres.user }}"
      POSTGRES_PASSWORD: "{{ postgres.password }}"
      POSTGRES_PORT: "{{ postgres.port }}"
