---
- name: Ensure rclone config dir exists
  ansible.builtin.file:
    path: "{{ rclone_data_root }}"
    state: directory
    mode: "0755"

- name: Add rclone.conf file
  ansible.builtin.template:
    src: rclone.conf.j2
    dest: "{{ rclone_data_root }}/rclone.conf"
    mode: "0644"
