---
- name: Ensures bookstack dir exists
  file:
    path: "{{ root_dir }}/bookstack"
    state: directory

- name: Ensures bookstack public uploads dir exists
  file:
    path: "{{ root_dir }}/bookstack/data/public"
    state: directory

- name: Ensures bookstack storage uploads dir exists
  file:
    path: "{{ root_dir }}/bookstack/data/storage"
    state: directory

- name: Create the bookstack container
  docker_container:
    name: bookstack
    image: solidnerd/bookstack:0.27.4
    restart_policy: unless-stopped
    networks:
      - name: web
      - name: internal
    volumes:
      - "{{ root_dir }}/bookstack/data/public:/var/www/bookstack/public/uploads"
      - "{{ root_dir }}/bookstack/data/storage:/var/www/bookstack/storage/uploads"
    labels:
      traefik.frontend.rule: "Host:wiki.wertwein.com"
      traefik.frontend.redirect.entryPoint: https
      traefik.docker.network: "web"
      traefik.port: "80"
      traefik.enable: "true"
    env:
      APP_URL: "https://wiki.wertwein.com"
      DB_HOST: "mariadb"
      DB_DATABASE: "bookstack"
      DB_USERNAME: "{{ mariadb.user }}"
      DB_PASSWORD: "{{ mariadb.password }}"
      NAMECHEAP_API_USER: "{{ namecheap_api_user }}"
      NAMECHEAP_API_KEY: "{{ namecheap_api_key }}"
