---
- name: Ensures grafana dir exists
  ansible.builtin.file:
    path: "{{ root_dir }}/grafana/data"
    state: directory
    mode: 0777

- name: Create the grafana container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:8.4.1
    restart_policy: always
    networks:
      - name: web
      - name: internal
    volumes:
      - "{{ root_dir }}/grafana/data:/var/lib/grafana"
    env:
      GF_DATABASE_TYPE: "mysql"
      GF_DATABASE_HOST: "mariadb"
      GF_DATABASE_USER: "{{ mariadb_user }}"
      GF_DATABASE_PASSWORD: "{{ mariadb_password }}"
    labels:
      traefik.http.routers.grafana.rule: "Host(`health.wertwein.com`)"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"
      traefik.enable: "true"
