---
- name: Ensures prometheus dir exists
  file:
    path: "{{ root_dir }}/prometheus/data"
    state: directory
    mode: 0777

- name: Adding prometheus configuration file
  template:
    src: prometheus.yml
    dest: "{{ root_dir }}/prometheus/prometheus.yml"
    mode: 0644

- name: Create the prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus:v2.33.4
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention=30d"
    restart_policy: always
    networks:
      - name: internal
    volumes:
      - "{{ root_dir }}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "{{ root_dir }}/prometheus/data:/prometheus"
