---
- name: Ensures portainer dir exists
  file:
    path: "{{ root_dir }}/portainer/data"
    state: directory

- name: Create the portainer container
  docker_container:
    name: portainer
    image: portainer/portainer:1.22.0
    restart_policy: unless-stopped
    networks:
      - name: web
    volumes:
      - "{{ root_dir }}/portainer/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      traefik.http.routers.portainer.rule: "Host(`docker.wertwein.com`)"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"
      traefik.enable: "true"
