---
all:
  hosts:
    eserver:
      ansible_host: wertwein.com
    vagrant:
      ansible_host: 192.168.56.10
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/vagrant/virtualbox/private_key
