---
- name: Ensures required system packages are installed
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3
    - python3-pip
    - python3-setuptools

- name: Add Docker signing key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add Docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
    state: present

- name: Install Docker
  apt:
    update_cache: true
    name: docker-ce
    state: latest

- name: Install Docker module for Python
  pip:
    name: docker

- name: Ensures docker dir exists
  file:
    path: "/etc/docker"
    state: directory
    mode: 0755

- name: Configure Docker daemon
  template:
    src: daemon.json.j2
    dest: "/etc/docker/daemon.json"
    mode: 0644
  notify: restart docker

- name: Log into registries
  docker_login:
    registry: "{{ item.registry }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
  loop: "{{ docker_auth }}"
  no_log: true

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Ensures the internal network exists
  docker_network:
    name: internal
    driver: bridge

- name: Ensures the web network exists
  docker_network:
    name: web
    driver: bridge
