---
- name: Create the Watchtower container
  docker_container:
    name: watchtower
    image: containrrr/watchtower:1.3.0
    restart_policy: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
    # Update containers every hour
    command: --schedule "0 * * * *" --cleanup --debug
