---
- name: Adding config.json file
  template:
    src: config.json.j2
    dest: "{{ docker.root_dir }}/config.json"
    mode: 0600

- name: Create the Watchtower container
  docker_container:
    name: watchtower
    image: containrrr/watchtower:1.3.0
    restart_policy: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ docker.root_dir }}/config.json:/config.json:ro"
    # Update containers every hour
    command: --schedule "0 * * * *" --cleanup --debug
