---
- name: Create the Watchtower container
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower:1.7.1
    restart_policy: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
    # Update containers at 05:00 every Saturday
    command: --schedule "0 5 * * 6" --cleanup --debug
