---
- name: Ensures http dir exists
  file:
    path: "{{ root_dir }}/httpd"
    state: directory
    mode: 0755

- name: Adding httpd.conf file
  copy:
    src: httpd.conf
    dest: "{{ root_dir }}/httpd/httpd.conf"
    mode: 0644

- name: Adding httpd-vhosts.conf file
  template:
    src: httpd-vhosts.conf.j2
    dest: "{{ root_dir }}/httpd/httpd-vhosts.conf"
    mode: 0644

- name: Ensures site dirs exists
  file:
    path: "{{ root_dir }}/httpd/{{ item.owner }}/{{ item.url }}"
    owner: "{{ item.owner }}"
    group: sftp
    state: directory
    mode: 0755
  with_items: "{{ httpd_sites }}"

- name: Create the httpd container
  docker_container:
    name: httpd
    image: httpd:2.4-alpine
    restart_policy: unless-stopped
    networks:
      - name: web
    volumes: "{{ lookup('template', 'volumes.yml.j2') | from_yaml }}"
    labels:
      traefik.http.routers.httpd.rule: "{% for site in httpd_sites %}Host(`{{ site.url }}`){% if not loop.last %} || {% endif %}{% endfor %}"
      traefik.http.services.httpd.loadbalancer.server.port: "80"
      traefik.enable: "true"
    env:
      VIRTUAL_HOST: "{{ httpd_sites | map(attribute='url') | join(',') }}"
