---
- name: Ensures sftp group exists
  ansible.builtin.group:
    name: sftp
    state: present

- name: Ensures sftp users exists
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash(salt=item.salt) }}"
    create_home: false
    shell: /sbin/nologin
    state: present
  with_items: "{{ sftp_users }}"
  no_log: true
