---
- name: Ensures sftp group exists
  group:
    name: sftp
    state: present

- name: Ensures sftp users exists
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512', item.salt) }}"
    create_home: false
    shell: /sbin/nologin
    state: present
  with_items: "{{ sftp_users }}"
  no_log: true
