---
ssh_users: "{{ vault_ssh_users }}"
sftp_users: "{{ vault_sftp_users }}"

traefik_user: "{{ vault_traefik_username }}"
traefik_password: "{{ vault_traefik_password }}"

acme_email: "{{ vault_acme_email }}"
acme_provider: namecheap

namecheap_api_user: "{{ vault_namecheap_username }}"
namecheap_api_key: "{{ vault_namecheap_key }}"

postgres_enabled: true
postgres_user: "{{ vault_postgres_username }}"
postgres_password: "{{ vault_postgres_password }}"

mariadb_enabled: true
mariadb_user: "{{ vault_mariadb_username }}"
mariadb_password: "{{ vault_mariadb_password }}"

ddclient_protocol: namecheap
ddclient_domains: "{{ vault_domains }}"

httpd_sites: "{{ vault_webserver_sites }}"

minecraft:
  bedrock:
    enabled: true
    server_name: Ye boiii
    players: "{{ vault_minecraft_bedrock_players }}"
#  ftb:
#    enabled: true
#    players: "{{ vault_minecraft_ftb_players }}"
