---
ssh_users: "{{ vault_ssh_users }}"
sftp_users: "{{ vault_sftp_users }}"

traefik_user: "{{ vault_traefik_username }}"
traefik_password: "{{ vault_traefik_password }}"
traefik_salt: "{{ vault_traefik_salt }}"

acme_email: "{{ vault_acme_email }}"
acme_provider: cloudflare
acme_domain: wertwein.com

cloudflare_dns_api_token: "{{ vault_cloudflare_dns_api_token }}"

postgres_enabled: true
postgres_user: "{{ vault_postgres_username }}"
postgres_password: "{{ vault_postgres_password }}"

mariadb_enabled: true
mariadb_user: "{{ vault_mariadb_username }}"
mariadb_password: "{{ vault_mariadb_password }}"

ddclient_protocol: cloudflare
ddclient_zone: wertwein.com
ddclient_token: "{{ vault_cloudflare_dns_api_token }}"
ddclient_hosts:
  - wertwein.com
  - "*.wertwein.com"

httpd_sites: "{{ vault_webserver_sites }}"

minecraft:
  bedrock:
    enabled: true
    server_name: Ye boiii
    players: "{{ vault_minecraft_bedrock_players }}"
#  ftb:
#    enabled: true
#    players: "{{ vault_minecraft_ftb_players }}"
