---
- name: Ensures yumme uploads dir exists
  ansible.builtin.file:
    path: "{{ root_dir }}/yumme/uploads"
    state: directory
    mode: 0755

- name: Create the yumme server container
  community.docker.docker_container:
    name: yumme-server
    image: ghcr.io/aesy/yumme-server:latest
    restart_policy: unless-stopped
    networks:
      - name: web
      - name: internal
    volumes:
      - "{{ root_dir }}/yumme/uploads:/app/uploads"
    labels:
      traefik.http.routers.yumme-server.rule: "Host(`yumme.wertwein.com`) && PathPrefix(`/api/v1`)"
      traefik.http.services.yumme-server.loadbalancer.server.port: "8080"
      traefik.enable: "true"
    env:
      DATABASE_HOST: mariadb
      DATABASE_USERNAME: "{{ mariadb_user }}"
      DATABASE_PASSWORD: "{{ mariadb_password }}"

- name: Create the yumme web container
  community.docker.docker_container:
    name: yumme-web
    image: ghcr.io/aesy/yumme-web:latest
    restart_policy: unless-stopped
    networks:
      - name: web
    labels:
      traefik.http.routers.yumme-web.rule: "Host(`yumme.wertwein.com`)"
      traefik.http.services.yumme-web.loadbalancer.server.port: "80"
      traefik.enable: "true"
